# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/wilmot_g/Soft/clion-2017.3.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/wilmot_g/Soft/clion-2017.3.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wilmot_g/RMIT/3D/IslandDefense

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wilmot_g/RMIT/3D/IslandDefense

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/wilmot_g/Soft/clion-2017.3.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/wilmot_g/Soft/clion-2017.3.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wilmot_g/RMIT/3D/IslandDefense/CMakeFiles /home/wilmot_g/RMIT/3D/IslandDefense/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wilmot_g/RMIT/3D/IslandDefense/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IslandDefense

# Build rule for target.
IslandDefense: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IslandDefense
.PHONY : IslandDefense

# fast build rule for target.
IslandDefense/fast:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/build
.PHONY : IslandDefense/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/main.cpp.s
.PHONY : main.cpp.s

srcs/Boat.o: srcs/Boat.cpp.o

.PHONY : srcs/Boat.o

# target to build an object file
srcs/Boat.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Boat.cpp.o
.PHONY : srcs/Boat.cpp.o

srcs/Boat.i: srcs/Boat.cpp.i

.PHONY : srcs/Boat.i

# target to preprocess a source file
srcs/Boat.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Boat.cpp.i
.PHONY : srcs/Boat.cpp.i

srcs/Boat.s: srcs/Boat.cpp.s

.PHONY : srcs/Boat.s

# target to generate assembly for a file
srcs/Boat.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Boat.cpp.s
.PHONY : srcs/Boat.cpp.s

srcs/Cannon.o: srcs/Cannon.cpp.o

.PHONY : srcs/Cannon.o

# target to build an object file
srcs/Cannon.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Cannon.cpp.o
.PHONY : srcs/Cannon.cpp.o

srcs/Cannon.i: srcs/Cannon.cpp.i

.PHONY : srcs/Cannon.i

# target to preprocess a source file
srcs/Cannon.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Cannon.cpp.i
.PHONY : srcs/Cannon.cpp.i

srcs/Cannon.s: srcs/Cannon.cpp.s

.PHONY : srcs/Cannon.s

# target to generate assembly for a file
srcs/Cannon.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Cannon.cpp.s
.PHONY : srcs/Cannon.cpp.s

srcs/Displayable.o: srcs/Displayable.cpp.o

.PHONY : srcs/Displayable.o

# target to build an object file
srcs/Displayable.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Displayable.cpp.o
.PHONY : srcs/Displayable.cpp.o

srcs/Displayable.i: srcs/Displayable.cpp.i

.PHONY : srcs/Displayable.i

# target to preprocess a source file
srcs/Displayable.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Displayable.cpp.i
.PHONY : srcs/Displayable.cpp.i

srcs/Displayable.s: srcs/Displayable.cpp.s

.PHONY : srcs/Displayable.s

# target to generate assembly for a file
srcs/Displayable.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Displayable.cpp.s
.PHONY : srcs/Displayable.cpp.s

srcs/Game.o: srcs/Game.cpp.o

.PHONY : srcs/Game.o

# target to build an object file
srcs/Game.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Game.cpp.o
.PHONY : srcs/Game.cpp.o

srcs/Game.i: srcs/Game.cpp.i

.PHONY : srcs/Game.i

# target to preprocess a source file
srcs/Game.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Game.cpp.i
.PHONY : srcs/Game.cpp.i

srcs/Game.s: srcs/Game.cpp.s

.PHONY : srcs/Game.s

# target to generate assembly for a file
srcs/Game.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Game.cpp.s
.PHONY : srcs/Game.cpp.s

srcs/Island.o: srcs/Island.cpp.o

.PHONY : srcs/Island.o

# target to build an object file
srcs/Island.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Island.cpp.o
.PHONY : srcs/Island.cpp.o

srcs/Island.i: srcs/Island.cpp.i

.PHONY : srcs/Island.i

# target to preprocess a source file
srcs/Island.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Island.cpp.i
.PHONY : srcs/Island.cpp.i

srcs/Island.s: srcs/Island.cpp.s

.PHONY : srcs/Island.s

# target to generate assembly for a file
srcs/Island.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Island.cpp.s
.PHONY : srcs/Island.cpp.s

srcs/Movable.o: srcs/Movable.cpp.o

.PHONY : srcs/Movable.o

# target to build an object file
srcs/Movable.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Movable.cpp.o
.PHONY : srcs/Movable.cpp.o

srcs/Movable.i: srcs/Movable.cpp.i

.PHONY : srcs/Movable.i

# target to preprocess a source file
srcs/Movable.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Movable.cpp.i
.PHONY : srcs/Movable.cpp.i

srcs/Movable.s: srcs/Movable.cpp.s

.PHONY : srcs/Movable.s

# target to generate assembly for a file
srcs/Movable.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Movable.cpp.s
.PHONY : srcs/Movable.cpp.s

srcs/Pellet.o: srcs/Pellet.cpp.o

.PHONY : srcs/Pellet.o

# target to build an object file
srcs/Pellet.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Pellet.cpp.o
.PHONY : srcs/Pellet.cpp.o

srcs/Pellet.i: srcs/Pellet.cpp.i

.PHONY : srcs/Pellet.i

# target to preprocess a source file
srcs/Pellet.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Pellet.cpp.i
.PHONY : srcs/Pellet.cpp.i

srcs/Pellet.s: srcs/Pellet.cpp.s

.PHONY : srcs/Pellet.s

# target to generate assembly for a file
srcs/Pellet.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Pellet.cpp.s
.PHONY : srcs/Pellet.cpp.s

srcs/Projectile.o: srcs/Projectile.cpp.o

.PHONY : srcs/Projectile.o

# target to build an object file
srcs/Projectile.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Projectile.cpp.o
.PHONY : srcs/Projectile.cpp.o

srcs/Projectile.i: srcs/Projectile.cpp.i

.PHONY : srcs/Projectile.i

# target to preprocess a source file
srcs/Projectile.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Projectile.cpp.i
.PHONY : srcs/Projectile.cpp.i

srcs/Projectile.s: srcs/Projectile.cpp.s

.PHONY : srcs/Projectile.s

# target to generate assembly for a file
srcs/Projectile.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Projectile.cpp.s
.PHONY : srcs/Projectile.cpp.s

srcs/Shape.o: srcs/Shape.cpp.o

.PHONY : srcs/Shape.o

# target to build an object file
srcs/Shape.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Shape.cpp.o
.PHONY : srcs/Shape.cpp.o

srcs/Shape.i: srcs/Shape.cpp.i

.PHONY : srcs/Shape.i

# target to preprocess a source file
srcs/Shape.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Shape.cpp.i
.PHONY : srcs/Shape.cpp.i

srcs/Shape.s: srcs/Shape.cpp.s

.PHONY : srcs/Shape.s

# target to generate assembly for a file
srcs/Shape.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Shape.cpp.s
.PHONY : srcs/Shape.cpp.s

srcs/Stats.o: srcs/Stats.cpp.o

.PHONY : srcs/Stats.o

# target to build an object file
srcs/Stats.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Stats.cpp.o
.PHONY : srcs/Stats.cpp.o

srcs/Stats.i: srcs/Stats.cpp.i

.PHONY : srcs/Stats.i

# target to preprocess a source file
srcs/Stats.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Stats.cpp.i
.PHONY : srcs/Stats.cpp.i

srcs/Stats.s: srcs/Stats.cpp.s

.PHONY : srcs/Stats.s

# target to generate assembly for a file
srcs/Stats.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Stats.cpp.s
.PHONY : srcs/Stats.cpp.s

srcs/UI.o: srcs/UI.cpp.o

.PHONY : srcs/UI.o

# target to build an object file
srcs/UI.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/UI.cpp.o
.PHONY : srcs/UI.cpp.o

srcs/UI.i: srcs/UI.cpp.i

.PHONY : srcs/UI.i

# target to preprocess a source file
srcs/UI.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/UI.cpp.i
.PHONY : srcs/UI.cpp.i

srcs/UI.s: srcs/UI.cpp.s

.PHONY : srcs/UI.s

# target to generate assembly for a file
srcs/UI.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/UI.cpp.s
.PHONY : srcs/UI.cpp.s

srcs/Waves.o: srcs/Waves.cpp.o

.PHONY : srcs/Waves.o

# target to build an object file
srcs/Waves.cpp.o:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Waves.cpp.o
.PHONY : srcs/Waves.cpp.o

srcs/Waves.i: srcs/Waves.cpp.i

.PHONY : srcs/Waves.i

# target to preprocess a source file
srcs/Waves.cpp.i:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Waves.cpp.i
.PHONY : srcs/Waves.cpp.i

srcs/Waves.s: srcs/Waves.cpp.s

.PHONY : srcs/Waves.s

# target to generate assembly for a file
srcs/Waves.cpp.s:
	$(MAKE) -f CMakeFiles/IslandDefense.dir/build.make CMakeFiles/IslandDefense.dir/srcs/Waves.cpp.s
.PHONY : srcs/Waves.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IslandDefense"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... srcs/Boat.o"
	@echo "... srcs/Boat.i"
	@echo "... srcs/Boat.s"
	@echo "... srcs/Cannon.o"
	@echo "... srcs/Cannon.i"
	@echo "... srcs/Cannon.s"
	@echo "... srcs/Displayable.o"
	@echo "... srcs/Displayable.i"
	@echo "... srcs/Displayable.s"
	@echo "... srcs/Game.o"
	@echo "... srcs/Game.i"
	@echo "... srcs/Game.s"
	@echo "... srcs/Island.o"
	@echo "... srcs/Island.i"
	@echo "... srcs/Island.s"
	@echo "... srcs/Movable.o"
	@echo "... srcs/Movable.i"
	@echo "... srcs/Movable.s"
	@echo "... srcs/Pellet.o"
	@echo "... srcs/Pellet.i"
	@echo "... srcs/Pellet.s"
	@echo "... srcs/Projectile.o"
	@echo "... srcs/Projectile.i"
	@echo "... srcs/Projectile.s"
	@echo "... srcs/Shape.o"
	@echo "... srcs/Shape.i"
	@echo "... srcs/Shape.s"
	@echo "... srcs/Stats.o"
	@echo "... srcs/Stats.i"
	@echo "... srcs/Stats.s"
	@echo "... srcs/UI.o"
	@echo "... srcs/UI.i"
	@echo "... srcs/UI.s"
	@echo "... srcs/Waves.o"
	@echo "... srcs/Waves.i"
	@echo "... srcs/Waves.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

